<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Laya.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="AwesomeAssertions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Layar.Core/Layar.Core.csproj" />
    <ProjectReference Include="../../src/Laya.Tokenization/Laya.Tokenization.csproj" />
    <ProjectReference Include="../../src/Laya.Onnx/Laya.Onnx.csproj" />
    <ProjectReference Include="../../src/Laya.TorchSharp/Laya.TorchSharp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TorchSharp-cpu" />
  </ItemGroup>
</Project>
